print("Hi My name is Bruno and Im going to ask you some question. Ok?")
answer=input()
print("What is your name?")
answer1=input()
print(" In what school you study or what is your job?")
answer2=input()
print("What are your hobby")
answer3=input()
print("What are the favorite videogame?")
answer4=input()
print("You prefer Play or Xbox?")
answer5=input()
print("You prefer a console or a pc gamer")
answer6=input()
print("What types of genres you like in vidiogames")
answer7=input()
print("What are your favorite movie?")
answer8=input()
print("You prefer superheros movies or horror movies?")
answer9=input()
print("And the last question. How is your day?")
answer10=input()