print("hola mundo")
print("My name is Bruno Angulo Flores.")
print("Im in ninth grade.")
print("My group is 9th D.")
print("I have various favorite foods Im going to say two tacos de cabeza, sushi and chilaquies.")
print("Mr Im very excited to see the new movie of venom because is going to appear carnage")